import React from 'react'
import Footer from '../Components/Footer'
import Header from '../Components/Header'
import img from '../media/privacidad.png'


function Privacidad() {
  return (
    <div className='page__privacidad'>
  
        
        <div className='box__privacidad'>
            <img src={img} alt="" />
            <h1>PRIVACIDAD</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br /> Excepturi soluta obcaecati repellat possimus praesentium tenetur fugit omnis, neque voluptatem debitis nesciunt accusantium recusandae id nostrum, quam commodi aliquam alias cupiditate odio molestiae modi. Corrupti quas doloremque soluta explicabo libero facere ab illum deleniti fugiat  <br />recusandae, velit, facilis quidem eius aut. Neque atque ut omnis illum officiis. Totam rem debitis, reiciendis deleniti fuga eum a dolorem, veniam delectus aspernatur quidem enim laborum ad nam! Aspernatur quam vitae doloribus corporis distinctio, debitis labore, alias eveniet ratione hic fugit maiores necessitatibus libero. <br />
        

            Nulla commodi cupiditate odio eligendi neque deserunt eaque rem provident. Harum ea eaque incidunt amet perferendis natus, nisi ducimus minima voluptatibus. Provident repudiandae temporibus accusantium eum aliquam inventore laborum magnam odio molestiae? Provident sunt id dolor fuga aperiam similique eum saepe sed sint voluptas quas pariatur esse odit voluptatem inventore rerum nam vel delectus earum reprehenderit voluptate in, temporibus et sequi? Deleniti voluptatibus animi cupiditate harum tempora assumenda accusantium illo architecto expedita vel iure nam odio, quis ipsam vitae, amet soluta laborum.
            <br />
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero quibusdam velit vel voluptas nihil nam, harum ipsum corrupti quo a asperiores animi praesentium porro odio fugit similique eius doloremque dolorum ratione sint eligendi assumenda eos, eum dolor. Sapiente deserunt pariatur ipsum asperiores doloremque consectetur iusto unde itaque tenetur, voluptatum labore quo error minima quaerat! Consequuntur vero ad exercitationem beatae assumenda, aspernatur et distinctio obcaecati, ex nobis architecto soluta dicta veritatis, sed voluptate unde quae laudantium libero dolores nemo maxime doloribus! Accusantium, neque eius expedita atque est vero sequi. Totam quam unde quasi doloribus corporis vel sequi voluptate fugiat? Dolore aut vero maiores reprehenderit distinctio voluptatibus, facilis mollitia incidunt dignissimos architecto placeat veniam modi tempora amet sint! Itaque culpa sequi fuga autem, dolorem libero odio quos magnam mollitia debitis. 
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!

            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!

            <br />Sed dolor debitis asperiores, quas explicabo quam magnam temporibus numquam qui unde ratione ipsum, omnis quod rem porro beatae illo! Vel tempore ea esse sit culpa fugiat voluptatem laboriosam reiciendis cum dignissimos doloribus impedit sapiente sequi quis accusantium aliquid soluta commodi cumque, nesciunt nam maxime ad. Laboriosam aperiam officia quaerat ut exercitationem vitae alias? Ad suscipit, mollitia modi dolores maiores, voluptatum nobis consequatur porro itaque debitis rem labore amet vero repellat quam?<br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem! <br />
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id quaerat provident voluptate maxime dicta perferendis quo illo blanditiis unde quidem? Similique atque optio aliquid doloribus, eos beatae dolores, aperiam voluptas commodi veritatis fugiat tempora delectus, molestias rem!
            
            </p>
        </div>
      
    </div>
  )
}

export default Privacidad